<?php

namespace QS\BookingBundle\Repository;

use QS\BookingBundle\Entity\Ticket;
use QS\BookingBundle\Entity\TicketPeriod;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExcludedPeriodByTicket(Ticket $ticket)
    {
        $qb = $this->createQueryBuilder('p')
            ->innerJoin('p.tickets', 'tp', 'WITH', 'tp.ticket = :ticket AND tp.action = :action')
            ->setParameters([
                ':ticket' => $ticket,
                ':action' => TicketPeriod::ACTION_EXCLUDE,
            ])
            ->getQuery()
            ->getResult()
        ;

        return $qb;
    }
}
