<?php

namespace QS\BookingBundle\Repository;

/**
 * PricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricesRepository extends \Doctrine\ORM\EntityRepository
{
}
