<?php

namespace QS\BookingBundle\Repository;

use QS\BookingBundle\Entity\Ticket;

/**
 * TicketPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketPriceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneByTicket(Ticket $ticket)
    {
        return $qb = $this->createQueryBuilder('tp')
            ->andWhere('tp.ticket = :ticket')
            ->setParameters([
                'ticket' => $ticket,
            ])
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
        ;
    }
}
