<?php

namespace QS\BookingBundle\Repository;

use QS\BookingBundle\Entity\Event;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function areExists($tickets)
    {
        $qb = $this->createQueryBuilder('t')->select('COUNT(t)');
        foreach ($tickets as $ticket) {
            $test = "t.id = '".$ticket->getId()."'";
            $qb->orWhere($test);
        }
        $r = $qb->getQuery()->getSingleScalarResult();

        return count($tickets) == $r;
    }

    public function getAllByEvent(Event $event)
    {
        return $this->createQueryBuilder('t')
            ->innerJoin('t.events', 'e', 'WITH', 'e = :event')
            ->innerJoin('t.ticketPeriods', 'tp')
            ->addSelect('tp')
            ->innerJoin('tp.period', 'p')
            ->addSelect('p')
            ->setParameters([
                'event' => $event,
            ])
            ->getQuery()
            ->getResult()
        ;
    }
}
