<?php

namespace QS\BookingBundle\Repository;

/**
 * TicketPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
