<?php

namespace QS\BookingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function areExists($tickets)
    {
        $qb = $this->createQueryBuilder('t')->select('COUNT(t)');
        foreach ($tickets as $ticket) {
            $test = "t.id = '".$ticket->getId()."'";
            $qb->orWhere($test);
        }
        $r = $qb->getQuery()->getSingleScalarResult();

        return count($tickets) == $r;
    }
}
