<?php

namespace QS\BookingBundle\Repository;

/**
 * EventPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
