<?php

namespace QS\BookingBundle\Repository;

use QS\BookingBundle\Entity\Event;
use QS\BookingBundle\Entity\EventPeriod;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByEventActions(Event $event, array $actions, $scalar = false)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->innerJoin('p.events', 'ep', 'WITH', 'ep.event = :event AND ep.action IN (:actions)')
                ->setParameters([
                    'event' => $event,
                    'actions' => $actions,
                ])
            ->getQuery()
        ;
        if ($scalar) return $qb->getScalarResult();
        return $qb->getResult();
    }
}
