<?php

namespace QS\BookingBundle\Repository;

/**
 * TicketPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
