qs_booking_home:
    path:     /
    defaults: { _controller: QSBookingBundle:Booking:index }

qs_booking_guichet:
    path:     /guichet/{slug}
    defaults:
        _controller: QSBookingBundle:Booking:guichet
    requirements:
        slug: '[\w-]+'

qs_booking_information:
    path:     /informations-visiteurs
    defaults: { _controller: QSBookingBundle:Booking:information }

qs_booking_checkout:
    path:     /paiement
    defaults: { _controller: QSBookingBundle:Booking:checkout }

qs_booking_confirmation:
    path:     /confirmation
    defaults: { _controller: QSBookingBundle:Booking:confirmation }

qs_booking_cgv:
    path:     /cgv
    defaults: { _controller: QSBookingBundle:Booking:cgv }

qs_booking_cgu:
    path:     /cgu
    defaults: { _controller: QSBookingBundle:Booking:cgu }

qs_booking_legal:
    path:     /mentions-legales
    defaults: { _controller: QSBookingBundle:Booking:legal }

qs_booking_404:
    path:     /404
    defaults: { _controller: QSBookingBundle:Booking:404 }

qs_booking_ajax_event_unavailability:
    path:     /ajax/event/{slug}/unavailability
    defaults:
        _controller: QSBookingBundle:Ajax:getUnavailabilityForEvent
    requirements:
        slug: '[\w-]+'

qs_booking_ajax_event_date_tickets:
    path:     /ajax/event/{slug}/{date}/tickets
    defaults:
        _controller: QSBookingBundle:Ajax:getAvailableTicketsByEventDate
    requirements:
        slug: '[\w-]+'
        slug: '[\d-]{10}'
