qs_booking_home:
    path:     /
    defaults: { _controller: QSBookingBundle:Booking:index }

qs_booking_guichet:
    path:     /guichet/{slug}
    defaults:
        _controller: QSBookingBundle:Booking:guichet
    requirements:
        slug: '[\w-]+'

qs_booking_information:
    path:     /informations-visiteurs/{orderId}
    defaults: { _controller: QSBookingBundle:Booking:information }
    requirements:
        orderId: '[\w-]+'

qs_booking_checkout:
    path:     /paiement/{orderId}
    defaults: { _controller: QSBookingBundle:Booking:checkout }
    requirements:
        orderId: '[\w-]+'

qs_booking_confirmation:
    path:     /confirmation/{orderId}
    defaults: { _controller: QSBookingBundle:Booking:confirmation }
    requirements:
        orderId: '[\w-]+'

qs_booking_cgv:
    path:     /cgv
    defaults: { _controller: QSBookingBundle:Booking:cgv }

qs_booking_cgu:
    path:     /cgu
    defaults: { _controller: QSBookingBundle:Booking:cgu }

qs_booking_legal:
    path:     /mentions-legales
    defaults: { _controller: QSBookingBundle:Booking:legal }

qs_booking_404:
    path:     /404
    defaults: { _controller: QSBookingBundle:Booking:404 }

qs_booking_ajax:
    path:     /ajax
    defaults:
        _controller: QSBookingBundle:Ajax:root

qs_booking_ajax_event_unavailability:
    path:     /ajax/event/{slug}/unavailability
    defaults:
        _controller: QSBookingBundle:Ajax:getUnavailabilityForEvent
    requirements:
        slug: '[\w-]+'
