services:
  qs_booking.bookingService:
    class: QS\BookingBundle\Service\BookingService
    arguments: ["@doctrine.orm.entity_manager"]
  qs_booking.periodService:
    class: QS\BookingBundle\Service\PeriodService
    arguments: ["@doctrine.orm.entity_manager"]
  qs_booking.validator.bookOrder:
    class: QS\BookingBundle\Validator\Constraints\BookOrderValidator
    arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@qs_booking.periodService"]
    tags:
      - { name: validator.constraint_validator, alias: qs_booking_bookOrder }
  qs_booking.validator.bookTicket:
    class: QS\BookingBundle\Validator\Constraints\BookTicketValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator, alias: qs_booking_bookTicket }
